"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, BrainCircuit, ChevronDown, Command, LogOut, Menu, Moon, Search, Settings, Sun, X } from "lucide-react";
import { useEffect, useState } from "react";
import { navItems, pageMeta } from "./data";

function Avatar() { return <span className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-indigo-400 to-violet-600 text-xs font-bold text-white">MP</span>; }

export function DashboardShell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const [open, setOpen] = useState(false); const [dark, setDark] = useState(false);
  const title = path === "/dashboard" ? "Overview" : pageMeta[path]?.title ?? "LectureMate";
  useEffect(() => setDark(document.documentElement.classList.contains("dark")), []);
  const toggle = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); };
  const sidebar = <aside className="flex h-full w-72 flex-col border-r border-slate-200/70 bg-white/80 p-4 backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/85">
    <div className="mb-8 flex items-center justify-between px-2"><Link href="/dashboard" className="flex items-center gap-2.5 text-lg font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-white shadow-lg shadow-indigo-200/70"><BrainCircuit size={20}/></span>Lecture<span className="-ml-2 text-indigo-600">Mate</span></Link><button onClick={() => setOpen(false)} className="lg:hidden"><X size={19}/></button></div>
    <button className="mb-5 flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-left text-xs text-slate-400 dark:border-white/10 dark:bg-white/5"><Search size={15}/><span className="flex-1">Search anything...</span><kbd className="rounded border border-slate-200 bg-white px-1.5 py-0.5 text-[10px] dark:border-white/10 dark:bg-white/10">⌘ K</kbd></button>
    <nav className="flex-1 space-y-1">{navItems.map(({label,href,icon:Icon}) => <Link key={href} onClick={() => setOpen(false)} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${path===href ? "bg-indigo-50 font-semibold text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300" : "text-slate-500 hover:bg-slate-100 hover:text-slate-900 dark:text-slate-400 dark:hover:bg-white/5 dark:hover:text-white"}`}><Icon size={17}/>{label}</Link>)}</nav>
    <Link href="/dashboard/settings" className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm ${path==="/dashboard/settings" ? "bg-indigo-50 font-semibold text-indigo-700" : "text-slate-500 dark:text-slate-400"}`}><Settings size={17}/>Settings</Link>
    <form action="/auth/logout" method="post" className="mb-4"><button type="submit" className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-500 dark:text-slate-400"><LogOut size={17}/>Sign out</button></form>
    <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3.5 dark:border-white/10 dark:bg-white/5"><div className="flex items-center gap-2.5"><Avatar/><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold dark:text-white">Maya Patel</p><span className="mt-1 inline-flex rounded-full bg-indigo-100 px-1.5 py-0.5 text-[9px] font-bold text-indigo-600 dark:bg-indigo-500/15 dark:text-indigo-300">PRO PLAN</span></div><ChevronDown size={14} className="text-slate-400"/></div><div className="mt-4"><div className="mb-1.5 flex justify-between text-[10px] font-medium text-slate-500"><span>Storage</span><span>3.4 GB / 10 GB</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-200 dark:bg-white/10"><div className="h-full w-[34%] rounded-full bg-indigo-600"/></div></div></div>
  </aside>;
  return <div className="min-h-screen bg-[#f7f8fc] text-slate-900 dark:bg-[#080b14] dark:text-slate-100"><div className="hidden fixed inset-y-0 left-0 z-30 lg:block">{sidebar}</div>{open && <><div className="fixed inset-0 z-40 bg-slate-950/35 backdrop-blur-sm lg:hidden" onClick={() => setOpen(false)}/><div className="fixed inset-y-0 left-0 z-50 lg:hidden">{sidebar}</div></>}<div className="lg:pl-72"><header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-slate-200/70 bg-[#f7f8fc]/75 px-5 backdrop-blur-xl dark:border-white/10 dark:bg-[#080b14]/75 sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setOpen(true)} className="lg:hidden"><Menu size={20}/></button><div><h1 className="text-base font-bold tracking-tight sm:text-lg">{title}</h1><p className="hidden text-xs text-slate-500 sm:block">Your learning space</p></div></div><div className="flex items-center gap-2 sm:gap-3"><button aria-label="Global search" className="hidden h-9 w-64 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-left text-xs text-slate-400 shadow-sm dark:border-white/10 dark:bg-white/5 sm:flex"><Search size={15}/><span className="flex-1">Search your workspace</span><Command size={13}/></button><button aria-label="Notifications" className="grid h-9 w-9 place-items-center rounded-xl text-slate-500 transition hover:bg-white dark:hover:bg-white/5"><Bell size={18}/></button><button aria-label="Toggle color theme" onClick={toggle} className="grid h-9 w-9 place-items-center rounded-xl text-slate-500 transition hover:bg-white dark:hover:bg-white/5">{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button className="flex items-center gap-2 rounded-xl p-1 sm:pr-2"><Avatar/><ChevronDown size={14} className="hidden text-slate-400 sm:block"/></button></div></header><main className="mx-auto max-w-[1600px] p-5 sm:p-8">{children}</main></div></div>;
}
