"use client";

import { AnimatePresence, motion } from "framer-motion";
import { AudioLines, Check, ChevronRight, Clock3, FileImage, FileText, FolderOpen, ImageIcon, Layers3, Link2, LoaderCircle, Presentation, Sparkles, UploadCloud, X, Youtube } from "lucide-react";
import { ChangeEvent, DragEvent, useEffect, useRef, useState } from "react";

const supported = [
  { label: "PDF", icon: FileText, tone: "text-rose-500 bg-rose-50 dark:bg-rose-500/10" },
  { label: "PPT/PPTX", icon: Presentation, tone: "text-orange-500 bg-orange-50 dark:bg-orange-500/10" },
  { label: "DOCX", icon: FileText, tone: "text-sky-500 bg-sky-50 dark:bg-sky-500/10" },
  { label: "TXT", icon: FileText, tone: "text-slate-500 bg-slate-100 dark:bg-white/10" },
  { label: "Images", icon: ImageIcon, tone: "text-fuchsia-500 bg-fuchsia-50 dark:bg-fuchsia-500/10" },
  { label: "MP3/WAV", icon: AudioLines, tone: "text-violet-500 bg-violet-50 dark:bg-violet-500/10" },
  { label: "YouTube", icon: Youtube, tone: "text-red-500 bg-red-50 dark:bg-red-500/10" },
] as const;

const stages = ["Upload complete", "Reading document", "Extracting text", "Building summary", "Creating notes", "Generating flashcards", "Preparing quiz", "Done"];
const recent = [["Neuroscience: Week 08", "lecture_08.pdf", "32 pages", "Today, 10:42 AM", "Ready"], ["Cognitive Science Seminar", "cognitive-seminar.mp3", "48 min", "Yesterday", "Ready"], ["Cellular Biology", "cell-biology.pptx", "24 slides", "Apr 18", "Ready"]];

type UploadState = "idle" | "uploading" | "processing" | "complete";

export function UploadWorkspace() {
  const [state, setState] = useState<UploadState>("idle"); const [progress, setProgress] = useState(0); const [stage, setStage] = useState(0); const [name, setName] = useState("Lecture_09_neuroplasticity.pdf"); const [dragging, setDragging] = useState(false); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { if (state !== "uploading") return; const id = setInterval(() => setProgress(p => { if (p >= 100) { clearInterval(id); setState("processing"); return 100; } return Math.min(100, p + 5); }), 90); return () => clearInterval(id); }, [state]);
  useEffect(() => { if (state !== "processing") return; const id = setInterval(() => setStage(s => { if (s >= stages.length - 1) { clearInterval(id); setState("complete"); return s; } return s + 1; }), 620); return () => clearInterval(id); }, [state]);
  function start(file?: File) { setName(file?.name || "Lecture_09_neuroplasticity.pdf"); setProgress(0); setStage(0); setState("uploading"); }
  function choose(e: ChangeEvent<HTMLInputElement>) { start(e.target.files?.[0]); e.target.value = ""; }
  function drop(e: DragEvent<HTMLDivElement>) { e.preventDefault(); setDragging(false); start(e.dataTransfer.files[0]); }
  return <div className="mx-auto max-w-[1500px]"><div className="mb-7"><p className="text-sm font-medium text-indigo-600">AI MATERIAL INTAKE</p><h2 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Add something worth learning.</h2><p className="mt-2 text-sm text-slate-500">Upload a file or bring in a YouTube lecture. LectureMate will take care of the rest.</p></div><div className="grid gap-6 xl:grid-cols-[1fr_310px]">
    <div className="space-y-6"><section onDragOver={e => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={drop} className={`relative overflow-hidden rounded-3xl border border-dashed p-6 transition sm:p-8 ${dragging ? "border-indigo-500 bg-indigo-50/70 dark:bg-indigo-500/10" : "border-indigo-200 bg-white/75 dark:border-indigo-400/20 dark:bg-white/[.03]"}`}><div className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-indigo-100/60 blur-3xl dark:bg-indigo-500/10"/>
      <AnimatePresence mode="wait">{state === "idle" ? <motion.div key="empty" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="relative py-8 text-center sm:py-12"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-indigo-600 text-white shadow-xl shadow-indigo-200"><UploadCloud size={28}/></span><h3 className="mt-5 text-lg font-bold">Drop your learning material here</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Drag and drop any lecture, document, or recording. Or browse files from your computer.</p><div className="mt-6 flex flex-wrap justify-center gap-2">{supported.map(({label,icon:Icon,tone})=><span key={label} className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-[11px] font-semibold ${tone}`}><Icon size={13}/>{label}</span>)}</div><div className="mt-7 flex flex-wrap justify-center gap-3"><button onClick={() => input.current?.click()} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-indigo-200 transition hover:-translate-y-0.5 hover:bg-indigo-700"><FolderOpen size={16}/> Browse files</button><button onClick={() => start()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-600 transition hover:bg-slate-50 dark:border-white/10 dark:bg-white/5 dark:text-slate-300"><Link2 size={16}/> Paste YouTube URL</button></div><input ref={input} onChange={choose} type="file" className="hidden" accept=".pdf,.ppt,.pptx,.doc,.docx,.txt,image/*,audio/*"/></motion.div> : <motion.div key="progress" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="relative py-3 sm:py-5"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10"><FileText size={22}/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-bold">{name}</p>{state === "complete" ? <span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-600">Ready to learn</span> : <button aria-label="Cancel upload" onClick={() => setState("idle")}><X size={17} className="text-slate-400"/></button>}</div><p className="mt-1 text-xs text-slate-500">{state === "uploading" ? `${progress}% uploaded · 8.4 MB of 12.1 MB` : state === "complete" ? "AI materials generated successfully" : "Our AI is transforming your material"}</p>{state === "uploading" && <div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><motion.div className="h-full rounded-full bg-indigo-600" animate={{width:`${progress}%`}}/></div>}</div></div>
        {state !== "uploading" && <div className="mt-8 rounded-2xl border border-slate-100 bg-slate-50/80 p-4 dark:border-white/10 dark:bg-white/[.03]"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-bold">AI processing timeline</p><p className="mt-1 text-xs text-slate-500">We&apos;re creating your study toolkit.</p></div>{state === "processing" && <LoaderCircle size={18} className="animate-spin text-indigo-600"/>}</div><div className="grid gap-2 sm:grid-cols-2">{stages.map((label,i)=>{ const active = state === "complete" || i <= stage; const current = state === "processing" && i === stage; return <motion.div key={label} initial={{opacity:.35}} animate={{opacity: active ? 1 : .35}} className="flex items-center gap-2.5 rounded-xl bg-white p-2.5 dark:bg-white/5"><span className={`grid h-5 w-5 place-items-center rounded-full ${active?"bg-emerald-500 text-white":"bg-slate-200 text-slate-400 dark:bg-white/10"}`}>{current ? <LoaderCircle size={11} className="animate-spin"/> : active ? <Check size={12}/> : <span className="text-[9px]">{i+1}</span>}</span><span className={`text-xs font-medium ${active?"text-slate-700 dark:text-slate-200":"text-slate-400"}`}>{label}</span></motion.div>})}</div></div>}
        {state === "complete" && <button onClick={() => setState("idle")} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-bold text-white"><Sparkles size={15}/> Upload another file <ChevronRight size={14}/></button>}</motion.div>}</AnimatePresence>
    </section>
    <section className="rounded-2xl border border-slate-200/70 bg-white/75 p-5 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/[.03]"><div className="flex items-center justify-between"><div><h3 className="font-bold">Recent uploads</h3><p className="mt-1 text-xs text-slate-500">Continue where you left off</p></div><button className="text-xs font-bold text-indigo-600">View all</button></div><div className="mt-5 space-y-2">{recent.map(([title,file,detail,date,status])=><div key={file} className="flex items-center gap-3 rounded-xl p-2 transition hover:bg-slate-50 dark:hover:bg-white/5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10"><FileText size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{title}</p><p className="truncate text-[10px] text-slate-400">{file} · {detail}</p></div><div className="text-right"><p className="text-[10px] font-bold text-emerald-600">{status}</p><p className="text-[9px] text-slate-400">{date}</p></div></div>)}</div></section>
    </div>
    <aside className="space-y-4"><section className="rounded-2xl border border-slate-200/70 bg-white/75 p-5 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/[.03]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-600 dark:bg-amber-500/10"><Sparkles size={17}/></span><h3 className="mt-4 text-sm font-bold">Make uploads work harder</h3><ul className="mt-3 space-y-3 text-xs leading-5 text-slate-500"><li>Use clear file names for easier organization.</li><li>Upload the original source for the most accurate results.</li><li>Large lectures are automatically split into focused sections.</li></ul></section><section className="rounded-2xl border border-slate-200/70 bg-white/75 p-5 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/[.03]"><h3 className="text-sm font-bold">Upload details</h3><div className="mt-4 space-y-4">{[["Accepted formats","PDF, PPTX, DOCX, TXT, MP3, WAV, JPG, PNG"],["Upload limit","500 MB per file"],["Processing time","Usually 1–3 minutes"]].map(([label,value])=><div key={label}><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300">{value}</p></div>)}</div></section><section className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-center justify-between"><span className="text-sm font-bold">Storage usage</span><span className="text-xs text-slate-400">34%</span></div><p className="mt-3 text-2xl font-bold">3.4 <span className="text-sm font-medium text-slate-400">GB / 10 GB</span></p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[34%] rounded-full bg-indigo-400"/></div><button className="mt-4 text-xs font-bold text-indigo-300">Manage plan →</button></section></aside>
  </div></div>;
}
