"use client";

import { motion } from "framer-motion";
import {
  ArrowRight, Bot, BrainCircuit, Check, ChevronDown, FileText, Headphones,
  Layers3, Menu, MessageSquareText, Moon, Play, Sparkles, Sun, Upload,
  WandSparkles, X, Zap
} from "lucide-react";
import { useEffect, useState } from "react";

const features = [
  [FileText, "AI Notes", "Turn every lecture into beautifully structured, complete notes.", "from-indigo-500 to-violet-500"],
  [Sparkles, "PDF Summarizer", "Surface the important ideas from dense documents in seconds.", "from-sky-500 to-cyan-500"],
  [BrainCircuit, "Quiz Generator", "Test your understanding with tailored practice questions.", "from-orange-400 to-amber-400"],
  [Layers3, "Flashcards", "Build lasting recall with smart, spaced-repetition cards.", "from-emerald-500 to-teal-400"],
  [WandSparkles, "Mind Maps", "See complex concepts and their connections at a glance.", "from-fuchsia-500 to-pink-500"],
  [MessageSquareText, "AI Chat", "Ask anything and get clear answers grounded in your material.", "from-violet-500 to-purple-500"],
  [Headphones, "Voice Notes", "Capture spoken thoughts and turn them into actionable ideas.", "from-rose-500 to-red-400"],
  [Zap, "Revision Planner", "Know exactly what to review, and when, before each exam.", "from-lime-500 to-green-500"],
] as const;

const testimonials = [
  ["LectureMate changed how I study. I used to spend hours rewriting notes—now I focus on actually understanding.", "Maya Patel", "Medical student, Stanford", "MP"],
  ["The quiz generator is incredibly good at finding the gaps I didn’t know I had. My grades went up within a month.", "James Okafor", "Computer Science, UCL", "JO"],
  ["I can upload a two-hour recording and have a calm, clear revision plan before I make coffee. Magic.", "Sofia Chen", "Law student, NYU", "SC"],
];

const faqs = [
  ["What can I upload to LectureMate?", "You can upload lecture recordings, PDFs, PowerPoint files, Word documents, images, and voice notes. We process the material and turn it into learning tools."],
  ["Is there a free plan?", "Yes. The free plan includes a monthly allowance to explore all core features, no card required."],
  ["How accurate is the AI?", "LectureMate keeps outputs tied closely to your source material. We encourage reviewing generated material, especially for high-stakes subjects."],
  ["Can I use LectureMate on my phone?", "Absolutely. The workspace is designed to feel great on phones, tablets, and desktops."],
];

function ThemeToggle() {
  const [dark, setDark] = useState(false);
  useEffect(() => { setDark(document.documentElement.classList.contains("dark")); }, []);
  function toggle() { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); }
  return <button onClick={toggle} className="grid h-9 w-9 place-items-center rounded-full text-slate-600 transition hover:bg-slate-100" aria-label="Toggle color theme">{dark ? <Sun size={17} /> : <Moon size={17} />}</button>;
}

function Nav() {
  const [open, setOpen] = useState(false);
  const links = ["Features", "Pricing", "About", "Contact"];
  return <header className="sticky top-0 z-50 border-b border-white/60 bg-white/75 backdrop-blur-xl">
    <nav className="container-page flex h-[72px] items-center justify-between">
      <a href="#top" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><BrainCircuit size={20}/></span><span>Lecture<span className="text-indigo-600">Mate</span></span></a>
      <div className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex">{links.map(x => <a key={x} href={`#${x.toLowerCase()}`} className="transition hover:text-indigo-600">{x}</a>)}</div>
      <div className="hidden items-center gap-3 md:flex"><ThemeToggle/><a href="#" className="px-3 py-2 text-sm font-semibold text-slate-700">Log in</a><a href="#pricing" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-700">Get started</a></div>
      <button className="md:hidden" onClick={() => setOpen(!open)} aria-label="Open navigation">{open ? <X/> : <Menu/>}</button>
    </nav>
    {open && <div className="container-page border-t border-slate-100 py-4 md:hidden">{links.map(x => <a key={x} onClick={() => setOpen(false)} href={`#${x.toLowerCase()}`} className="block py-3 font-medium">{x}</a>)}<a href="#pricing" className="mt-2 block rounded-xl bg-indigo-600 px-4 py-3 text-center font-semibold text-white">Get started free</a></div>}
  </header>;
}

function DashboardMockup() { return <div className="relative mx-auto w-full max-w-[610px] animate-float rounded-[26px] border border-slate-200/80 bg-white p-2 shadow-2xl shadow-indigo-950/15">
  <div className="overflow-hidden rounded-[20px] border border-slate-100 bg-[#f8f9ff]">
    <div className="flex h-10 items-center gap-1.5 border-b border-slate-100 bg-white px-4"><i className="h-2.5 w-2.5 rounded-full bg-rose-300"/><i className="h-2.5 w-2.5 rounded-full bg-amber-300"/><i className="h-2.5 w-2.5 rounded-full bg-emerald-300"/><div className="ml-6 h-5 w-40 rounded-md bg-slate-100"/></div>
    <div className="grid grid-cols-[130px_1fr] sm:grid-cols-[150px_1fr]">
      <aside className="hidden min-h-[340px] border-r border-slate-100 bg-white p-3 sm:block"><div className="mb-5 flex items-center gap-1.5 text-xs font-bold"><BrainCircuit size={15} className="text-indigo-600"/> LectureMate</div>{["Overview", "My Library", "Flashcards", "Planner"].map((x,i)=><div key={x} className={`mb-1 rounded-lg px-2.5 py-2 text-[10px] ${i===0 ? "bg-indigo-50 font-semibold text-indigo-600" : "text-slate-500"}`}>{x}</div>)}</aside>
      <main className="p-4 sm:p-5"><div className="mb-5 flex items-start justify-between"><div><p className="text-[10px] font-medium text-slate-400">Monday, April 21</p><h3 className="mt-1 text-sm font-bold sm:text-base">Good morning, Maya <span>✦</span></h3></div><div className="grid h-7 w-7 place-items-center rounded-full bg-indigo-100 text-[9px] font-bold text-indigo-700">MP</div></div>
      <div className="mb-4 rounded-xl bg-gradient-to-br from-indigo-600 to-violet-500 p-4 text-white"><p className="text-[10px] text-indigo-100">Continue learning</p><p className="mt-1 text-xs font-bold sm:text-sm">Introduction to Neurobiology</p><div className="mt-3 flex items-center gap-2"><div className="h-1.5 flex-1 rounded-full bg-white/20"><div className="h-full w-[68%] rounded-full bg-white"/></div><span className="text-[9px]">68%</span></div></div>
      <div className="mb-3 flex items-center justify-between"><h4 className="text-xs font-bold">Your study tools</h4><span className="text-[10px] font-medium text-indigo-600">View all</span></div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border border-slate-100 bg-white p-3"><div className="mb-2 grid h-6 w-6 place-items-center rounded-lg bg-emerald-50 text-emerald-600"><FileText size={13}/></div><p className="text-[10px] font-semibold">AI Notes</p><p className="text-[9px] text-slate-400">12 files</p></div><div className="rounded-xl border border-slate-100 bg-white p-3"><div className="mb-2 grid h-6 w-6 place-items-center rounded-lg bg-orange-50 text-orange-500"><BrainCircuit size={13}/></div><p className="text-[10px] font-semibold">Practice quiz</p><p className="text-[9px] text-slate-400">8 questions</p></div></div></main>
    </div>
  </div>
  <div className="absolute -left-5 top-1/2 hidden -translate-y-1/2 rounded-xl border border-white bg-white/95 p-3 shadow-xl sm:block"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-emerald-100 text-emerald-600"><Check size={14}/></span><div><p className="text-[10px] font-bold">Notes ready</p><p className="text-[9px] text-slate-400">Just now</p></div></div></div>
</div>; }

function AiWorkspace() {
  const [tilt, setTilt] = useState({ x: 0, y: 0 });
  return <div className="relative mx-auto w-full max-w-[660px] py-8 sm:py-10" onMouseMove={(e) => { const r = e.currentTarget.getBoundingClientRect(); setTilt({ x: (e.clientX-r.left-r.width/2)/30, y: (e.clientY-r.top-r.height/2)/30 }); }} onMouseLeave={() => setTilt({x:0,y:0})}>
    <motion.div animate={{ rotateY: tilt.x, rotateX: -tilt.y }} transition={{ type:"spring", stiffness:90, damping:18 }} style={{transformStyle:"preserve-3d"}} className="relative overflow-hidden rounded-[26px] border border-white/80 bg-white/90 p-2 shadow-[0_30px_80px_-24px_rgba(49,46,129,.35)] backdrop-blur-xl">
      <div className="overflow-hidden rounded-[20px] border border-slate-100 bg-[#f8f9ff]"><div className="flex h-11 items-center justify-between border-b border-slate-100 bg-white px-4"><div className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-rose-300"/><i className="h-2 w-2 rounded-full bg-amber-300"/><i className="h-2 w-2 rounded-full bg-emerald-300"/><span className="ml-3 text-[10px] font-semibold text-slate-400">workspace.lecturemate.ai</span></div><Sparkles size={14} className="text-indigo-500"/></div>
      <div className="grid min-h-[355px] grid-cols-[110px_1fr] sm:grid-cols-[135px_1fr]"><aside className="border-r border-slate-100 bg-white p-3"><div className="mb-5 hidden items-center gap-1.5 text-[10px] font-bold sm:flex"><span className="grid h-5 w-5 place-items-center rounded-md bg-indigo-600 text-white"><BrainCircuit size={11}/></span> LectureMate</div>{[[FileText,"Library"],[Sparkles,"AI Studio"],[Layers3,"Flashcards"],[MessageSquareText,"AI Chat"]].map(([I,label],i)=>{const Icon=I as typeof FileText; return <div key={label as string} className={`mb-1 flex items-center gap-2 rounded-lg px-2 py-2 text-[9px] ${i===1?"bg-indigo-50 font-bold text-indigo-600":"text-slate-500"}`}><Icon size={12}/><span className="hidden sm:inline">{label as string}</span></div>})}</aside>
      <main className="p-3 sm:p-4"><div className="flex items-start justify-between"><div><p className="text-[9px] font-medium text-indigo-600">AI WORKSPACE</p><h3 className="mt-1 text-xs font-bold sm:text-sm">Neuroscience: Week 08</h3></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-bold text-emerald-600">Processed</span></div><div className="mt-3 grid grid-cols-[.95fr_1.05fr] gap-2"><div className="rounded-xl border border-slate-100 bg-white p-2.5"><div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-md bg-rose-50 text-rose-500"><FileText size={12}/></span><div><p className="text-[9px] font-semibold">lecture_08.pdf</p><p className="text-[8px] text-slate-400">32 pages · Uploaded</p></div></div><div className="mt-3 space-y-1.5"><i className="block h-1.5 w-full rounded bg-slate-100"/><i className="block h-1.5 w-4/5 rounded bg-slate-100"/><i className="block h-1.5 w-3/5 rounded bg-slate-100"/></div></div><div className="rounded-xl bg-gradient-to-br from-indigo-600 to-violet-500 p-2.5 text-white"><div className="flex items-center justify-between"><p className="text-[9px] font-bold">Generated summary</p><Sparkles size={11}/></div><p className="mt-2 text-[8px] leading-3 text-indigo-100">Neurons communicate through electrical and chemical signals, forming the basis of...</p><p className="mt-2 text-[8px] font-bold">View summary →</p></div></div><div className="mt-2 grid grid-cols-3 gap-2"><div className="rounded-xl border border-slate-100 bg-white p-2"><Layers3 size={12} className="text-emerald-500"/><p className="mt-1 text-[8px] font-bold">24 Flashcards</p><p className="text-[7px] text-slate-400">Ready to review</p></div><div className="rounded-xl border border-slate-100 bg-white p-2"><BrainCircuit size={12} className="text-amber-500"/><p className="mt-1 text-[8px] font-bold">12 Question Quiz</p><p className="text-[7px] text-slate-400">Test yourself</p></div><div className="rounded-xl border border-slate-100 bg-white p-2"><WandSparkles size={12} className="text-fuchsia-500"/><p className="mt-1 text-[8px] font-bold">Mind Map</p><p className="text-[7px] text-slate-400">Explore concepts</p></div></div><div className="mt-2 flex items-center gap-2 rounded-xl border border-indigo-100 bg-indigo-50/70 p-2"><span className="grid h-5 w-5 place-items-center rounded-full bg-indigo-600 text-white"><Bot size={11}/></span><p className="flex-1 text-[8px] text-slate-500">Ask anything about this lecture...</p><ArrowRight size={11} className="text-indigo-600"/></div><p className="mt-3 text-[8px] font-bold text-slate-500">Recent uploads</p><div className="mt-1 flex gap-2">{["Cognitive Science.pdf","Cell Biology.pptx","Organic Chemistry.mp3"].map(x=><span key={x} className="truncate rounded-md bg-white px-2 py-1 text-[7px] text-slate-400 shadow-sm">{x}</span>)}</div></main></div></div>
    </motion.div>
    {[[-15,"top-5","Notes generated",FileText,"text-emerald-600","bg-emerald-50"],[95,"top-20","Quiz ready",BrainCircuit,"text-amber-600","bg-amber-50"],[-10,"bottom-0","Flashcards created",Layers3,"text-indigo-600","bg-indigo-50"],[100,"bottom-12","AI explaining Chapter 8",Bot,"text-violet-600","bg-violet-50"]].map(([left,position,text,Icon,color,bg],i)=>{const I=Icon as typeof FileText; return <motion.div key={text as string} animate={{y:[0,i%2?8:-8,0]}} transition={{duration:4+i,repeat:Infinity,ease:"easeInOut"}} style={{left:`${left}%`}} className={`absolute ${position} hidden items-center gap-2 rounded-xl border border-white/80 bg-white/80 px-3 py-2 shadow-xl shadow-indigo-950/10 backdrop-blur-xl lg:flex`}><span className={`grid h-6 w-6 place-items-center rounded-lg ${bg as string} ${color as string}`}><I size={12}/></span><span className="text-[10px] font-semibold text-slate-700">{text as string}</span><Check size={12} className="text-emerald-500"/></motion.div>})}
  </div>;
}

export function LandingPage() { const [faq, setFaq] = useState<number | null>(0); return <div id="top" className="overflow-hidden">
  <Nav />
  <main>
    <section className="relative isolate pb-24 pt-20 sm:pb-32 sm:pt-28"><div className="hero-grid absolute inset-x-0 top-0 -z-20 h-[720px]"/><div className="hero-noise absolute inset-0 -z-10"/><div className="absolute -left-24 top-0 -z-10 h-80 w-80 rounded-full bg-indigo-200/55 blur-3xl" style={{animation:"drift 9s ease-in-out infinite"}}/><div className="absolute right-0 top-16 -z-10 h-96 w-96 rounded-full bg-violet-200/50 blur-3xl" style={{animation:"drift 12s ease-in-out infinite reverse"}}/><div className="container-page grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]">
      <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.6}}><span className="eyebrow border-indigo-200/70 bg-white/70 shadow-sm backdrop-blur"><Sparkles size={13}/> The AI study system for ambitious students</span><h1 className="mt-7 max-w-2xl text-5xl font-bold leading-[.98] tracking-[-.06em] text-slate-950 sm:text-6xl lg:text-7xl">Turn every lecture into <span className="bg-gradient-to-r from-indigo-600 via-violet-600 to-indigo-500 bg-[length:200%_auto] bg-clip-text text-transparent" style={{animation:"sheen 5s ease infinite"}}>exam success.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-slate-600 sm:text-lg">Your personal AI workspace turns every lecture, PDF, and recording into clear study material you will actually remember.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#pricing" className="inline-flex items-center gap-2 rounded-2xl bg-indigo-600 px-5 py-3.5 text-sm font-semibold text-white shadow-[0_12px_30px_rgba(79,70,229,.3)] transition hover:-translate-y-0.5 hover:bg-indigo-700">Start learning free <ArrowRight size={16}/></a><button className="inline-flex items-center gap-2 rounded-2xl border border-white bg-white/80 px-5 py-3.5 text-sm font-semibold text-slate-700 shadow-sm backdrop-blur transition hover:bg-white"><span className="grid h-5 w-5 place-items-center rounded-full bg-indigo-100 text-indigo-600"><Play size={10} fill="currentColor"/></span> See how it works</button></div><div className="mt-8 flex items-center gap-3 text-xs text-slate-500"><div className="flex -space-x-2">{["bg-orange-200","bg-sky-200","bg-violet-200","bg-emerald-200"].map((c,i)=><span key={i} className={`grid h-7 w-7 place-items-center rounded-full border-2 border-white ${c} text-[8px] font-bold text-slate-600`}>{["M","J","S","A"][i]}</span>)}</div><span>Trusted by <b className="text-slate-700">50,000+ students</b></span></div></motion.div>
      <motion.div initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} transition={{duration:.7,delay:.15}}><AiWorkspace/></motion.div>
    </div></section>
    <section className="border-y border-slate-100 bg-white/70 py-9 backdrop-blur"><div className="container-page"><p className="mb-5 text-center text-[10px] font-bold tracking-[.18em] text-slate-400">USED BY STUDENTS FROM</p><div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-4 text-base font-bold tracking-tight text-slate-400 sm:gap-x-16"><span className="font-serif text-xl">MIT</span><span>Stanford</span><span className="font-serif text-xl">Harvard</span><span>IIT</span><span>NIT</span></div></div></section>
    <section className="container-page py-12 sm:py-16"><div className="grid grid-cols-2 divide-x divide-y divide-slate-100 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm sm:grid-cols-4 sm:divide-y-0">{[["50K+","Students"],["1M+","Notes generated"],["99%","Satisfaction"],["10M+","Flashcards"]].map(([value,label])=><div key={label} className="px-5 py-6 text-center sm:px-7 sm:py-8"><p className="text-2xl font-bold tracking-tight text-indigo-600 sm:text-3xl">{value}</p><p className="mt-1 text-xs font-medium text-slate-500">{label}</p></div>)}</div></section>
    <section id="features" className="container-page py-24 sm:py-32"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">Powerful by design</span><h2 className="section-heading mt-5">Everything you need to <span className="text-indigo-600">learn deeply.</span></h2><p className="muted mt-5">One calm workspace for every step of your study process.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,body,gradient],i)=><motion.article key={title} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}} className="group rounded-2xl border border-slate-100 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-200/50"><div className={`mb-5 grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br ${gradient} text-white shadow-lg`}><Icon size={20}/></div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-indigo-600 opacity-0 transition group-hover:opacity-100">Explore <ArrowRight size={14}/></span></motion.article>)}</div></section>
    <section id="about" className="bg-slate-950 py-24 text-white sm:py-32"><div className="container-page grid items-center gap-14 lg:grid-cols-2"><div><span className="inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-semibold text-indigo-200">Simple by nature</span><h2 className="mt-5 text-3xl font-bold tracking-tight sm:text-5xl">From lecture to clarity in three simple steps.</h2><p className="mt-5 max-w-lg leading-7 text-slate-400">Let LectureMate handle the busywork, so your energy stays where it matters: learning.</p><div className="mt-8 space-y-5">{[[Upload,"Upload your material","Drop in any file—from a lecture recording to a slide deck."],[Bot,"Let AI do the work","We extract, organize, and connect the important ideas."],[BrainCircuit,"Learn faster","Review in the format that helps knowledge stick."]].map(([Icon,title,body],i)=>{const I=Icon as typeof Upload; return <div key={title as string} className="flex gap-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-500/20 text-indigo-300"><I size={18}/></span><div><p className="font-semibold"><span className="mr-2 text-indigo-300">0{i+1}.</span>{title as string}</p><p className="mt-1 text-sm text-slate-400">{body as string}</p></div></div>})}</div></div><div className="rounded-3xl border border-white/10 bg-white/[.06] p-5 backdrop-blur"><div className="rounded-2xl border border-white/10 bg-slate-900 p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-500"><Upload size={19}/></span><div><p className="text-sm font-semibold">Upload new material</p><p className="text-xs text-slate-400">PDF, PPT, DOCX, MP3, MP4, image</p></div></div><div className="mt-6 rounded-xl border border-dashed border-indigo-400/50 bg-indigo-500/10 px-4 py-9 text-center"><Upload className="mx-auto text-indigo-300" size={24}/><p className="mt-3 text-sm font-medium">Drop your files here</p><p className="mt-1 text-xs text-slate-400">or browse from your computer</p></div><div className="mt-4 flex items-center justify-between rounded-xl bg-white/5 p-3"><span className="text-xs text-slate-300">Lecture_08_neuroscience.mp3</span><span className="text-xs font-semibold text-emerald-400">Ready</span></div></div></div></div></section>
    <section className="container-page py-24 sm:py-32"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">Loved by learners</span><h2 className="section-heading mt-5">Made for ambitious minds.</h2></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{testimonials.map(([quote,name,role,initial])=><figure key={name} className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="text-amber-400">★★★★★</div><blockquote className="mt-4 text-[15px] leading-7 text-slate-600">“{quote}”</blockquote><figcaption className="mt-6 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-indigo-100 text-xs font-bold text-indigo-700">{initial}</span><div><p className="text-sm font-semibold">{name}</p><p className="text-xs text-slate-500">{role}</p></div></figcaption></figure>)}</div></section>
    <section id="pricing" className="bg-indigo-50/70 py-24 sm:py-32"><div className="container-page"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">Simple, honest pricing</span><h2 className="section-heading mt-5">Invest in your best semester.</h2><p className="muted mt-5">Start free. Upgrade whenever you’re ready.</p></div><div className="mx-auto mt-14 grid max-w-4xl gap-5 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-7"><p className="font-bold">Free</p><p className="mt-3 text-4xl font-bold">$0<span className="text-base font-medium text-slate-400"> / month</span></p><p className="mt-3 text-sm text-slate-500">Everything you need to get started.</p><a href="#" className="mt-6 block rounded-xl border border-slate-200 py-3 text-center text-sm font-semibold">Get started</a><ul className="mt-6 space-y-3 text-sm text-slate-600">{["5 uploads per month","AI notes & summaries","Basic flashcards"].map(x=><li key={x} className="flex gap-2"><Check size={17} className="text-emerald-500"/>{x}</li>)}</ul></div><div className="relative rounded-2xl bg-indigo-600 p-7 text-white shadow-2xl shadow-indigo-300"><span className="absolute right-5 top-0 -translate-y-1/2 rounded-full bg-emerald-400 px-3 py-1 text-[11px] font-bold text-emerald-950">MOST POPULAR</span><p className="font-bold">Pro</p><p className="mt-3 text-4xl font-bold">$12<span className="text-base font-medium text-indigo-200"> / month</span></p><p className="mt-3 text-sm text-indigo-100">For students who want to excel.</p><a href="#" className="mt-6 block rounded-xl bg-white py-3 text-center text-sm font-semibold text-indigo-700">Start 7-day free trial</a><ul className="mt-6 space-y-3 text-sm text-indigo-100">{["Unlimited uploads","Advanced quizzes & mind maps","Personal revision planner","Priority AI processing"].map(x=><li key={x} className="flex gap-2"><Check size={17} className="text-emerald-300"/>{x}</li>)}</ul></div></div></div></section>
    <section className="container-page py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><span className="eyebrow">FAQ</span><h2 className="section-heading mt-5">Questions, answered.</h2><p className="muted mt-5">Still curious? <a href="#contact" className="font-semibold text-indigo-600">Talk to our team.</a></p></div><div className="divide-y divide-slate-200">{faqs.map(([q,a],i)=><div key={q} className="py-4"><button onClick={() => setFaq(faq===i?null:i)} className="flex w-full items-center justify-between gap-5 text-left font-semibold"><span>{q}</span><ChevronDown size={19} className={`shrink-0 text-indigo-600 transition ${faq===i?"rotate-180":""}`}/></button>{faq===i&&<p className="max-w-2xl pt-3 text-sm leading-6 text-slate-600">{a}</p>}</div>)}</div></div></section>
    <section id="contact" className="container-page pb-24"><div className="relative overflow-hidden rounded-3xl bg-slate-950 px-6 py-16 text-center text-white sm:px-12 sm:py-20"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-indigo-600/40 blur-3xl"/><div className="relative"><span className="eyebrow border-white/10 bg-white/10 text-indigo-200">Your next study session starts here</span><h2 className="mx-auto mt-5 max-w-2xl text-3xl font-bold tracking-tight sm:text-5xl">Turn today’s lecture into tomorrow’s confidence.</h2><a href="#pricing" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3.5 text-sm font-bold text-indigo-700 transition hover:bg-indigo-50">Start learning for free <ArrowRight size={16}/></a><p className="mt-4 text-xs text-slate-400">No credit card required</p></div></div></section>
  </main>
  <footer className="border-t border-slate-200 bg-white py-10"><div className="container-page flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><a href="#top" className="flex items-center gap-2 font-bold"><span className="grid h-7 w-7 place-items-center rounded-lg bg-indigo-600 text-white"><BrainCircuit size={15}/></span>Lecture<span className="-ml-2 text-indigo-600">Mate</span></a><p className="mt-2 text-xs text-slate-500">Transform lectures into knowledge.</p></div><div className="flex gap-5 text-xs font-medium text-slate-500"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Support</a></div><p className="text-xs text-slate-400">© 2026 LectureMate</p></div></footer>
</div>; }
